# Site settings
title: Блог Михаила Пивоваренко.
description: Сайт-портфолио Михаила Пивоваренко.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mishapivo.github.io" # the base hostname & protocol for your site e.g. http://mishapivo.github.io

# User settings
username: mishapivo
user_description: Фрилансер Mikhail Pivovarenko
user_title: Mikhail Pivovarenko
email: mishapivo@gmail.com
twitter_username: mishapivo
github_username:  mishapivo
gplus_username:  mishapivo
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']